run:
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  unused:
    check-exported: false
  unparam:
    check-exported: false
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - gochecknoinits
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - funlen
        - gocyclo
        - goconst
        - dupl
    - path: cmd/
      linters:
        - gocyclo
        - funlen
        - gomnd
    - path: pkg/service/
      linters:
        - gosec  # Service files need specific permissions
    - path: pkg/config/
      linters:
        - gosec  # TLS config may need InsecureSkipVerify
    - path: pkg/metrics/
      linters:
        - gosec  # Metrics server config
    - path: pkg/auth/
      linters:
        - gocritic  # JWT handling may have specific patterns
    - path: pkg/relay/
      linters:
        - govet  # Shadow variables in complex logic
    - path: pkg/p2p/
      linters:
        - gocritic  # P2P logic may have specific patterns
  max-issues-per-linter: 0
  max-same-issues: 0
