version: 2

project_name: cloudbridge-client

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod tidy

builds:
  - id: cloudbridge
    main: ./cmd/cloudbridge-client
    binary: cloudbridge-client
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}'
    files:
      - README.md
      - LICENSE*
    wrap_in_directory: false

checksum:
  name_template: 'checksums.txt'

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: auto
