version: 2

project_name: cloudbridge-client

env:
  - CGO_ENABLED=0

before:
  hooks:
    - go mod download

builds:
  - id: cloudbridge-client
    main: ./cmd/cloudbridge-client
    binary: cloudbridge-client
    goos: [linux, windows, darwin]
    goarch: [amd64, arm64]
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: archive
    builds: [cloudbridge-client]
    name_template: '{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}-v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
    wrap_in_directory: false

checksum:
  name_template: 'checksums.txt'

sboms:
  - artifacts: archive
    formats: [cyclonedx, spdx]

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^chore:'
      - '^docs:'
      - '^test:'

release:
  draft: false
  prerelease: auto
  name_template: 'CloudBridge Client {{ .Version }}'

snapshot:
  name_template: 'snapshot-{{ .ShortCommit }}'
