version: 2

project_name: cloudbridge-client

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: cloudbridge-client
    binary: cloudbridge-client
    main: ./cmd/cloudbridge-client/
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}
      - -X main.buildType=release
      - -X main.buildOS={{.Os}}
      - -X main.buildArch={{.Arch}}

  - id: quic-tester
    binary: quic-tester
    main: ./cmd/quic-tester/
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
    ignore:
      - goos: darwin
        goarch: "386"
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}
      - -X main.buildType=release

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - config-example.yaml
      - config-production.yaml

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-SNAPSHOT-{{ .ShortCommit }}"

git:
  # Ensure we're building from the right tag
  ignore_tags:
    - "*-rc*"
    - "*-alpha*"
    - "*-beta*"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  draft: false
  replace_existing_draft: false
  make_latest: true
  name_template: "{{.ProjectName}} {{.Version}}"
  header: |
    ## 🚀 CloudBridge Client {{.Version}}
    
    This release includes both the main CloudBridge Client and the QUIC Tester utility.
    
    ### 📦 Binaries Included:
    - **cloudbridge-client**: Main P2P mesh networking client
    - **quic-tester**: QUIC protocol testing utility
    
    ### 🏗️ Supported Platforms:
    - Linux (amd64, arm64, 386)  
    - Windows (amd64, arm64, 386)
    - macOS (amd64, arm64)
    
    ### 📋 Installation:
    1. Download the appropriate archive for your platform
    2. Extract the binaries
    3. Copy `config-example.yaml` to `config.yaml` and configure
    4. Run `./cloudbridge-client --help` for usage instructions
