# GoReleaser configuration for CloudBridge Client
# https://goreleaser.com/

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: cloudbridge-client
    binary: cloudbridge-client
    main: ./cmd/cloudbridge-client
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}
      - -X main.commit={{.Commit}}
    env:
      - CGO_ENABLED=0

  - id: quic-tester
    binary: quic-tester
    main: ./cmd/quic-tester
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - 386
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.buildTime={{.Date}}
      - -X main.commit={{.Commit}}
    env:
      - CGO_ENABLED=0

archives:
  - id: cloudbridge-client
    builds:
      - cloudbridge-client
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - config-example.yaml
      - README.md
      - LICENSE
    name_template: "cloudbridge-client_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: quic-tester
    builds:
      - quic-tester
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
    name_template: "quic-tester_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: full-package
    builds:
      - cloudbridge-client
      - quic-tester
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - config-example.yaml
      - README.md
      - LICENSE
    name_template: "cloudbridge-client_{{ .Version }}_{{ .Os }}_{{ .Arch }}_full"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: 2gc-dev
    name: relay-client
  name_template: "CloudBridge Client {{ .Version }}"
  header: |
    ## CloudBridge Client {{ .Version }}
    
    This release includes both the main CloudBridge Client and the QUIC Tester utility.
    
    ### Binaries Included:
    - **cloudbridge-client**: Main P2P mesh networking client
    - **quic-tester**: QUIC protocol testing utility
    
    ### Supported Platforms:
    - Linux (amd64, arm64, 386)
    - Windows (amd64, arm64, 386)
    - macOS (amd64, arm64)
    
    ### Installation:
    1. Download the appropriate archive for your platform
    2. Extract the binaries
    3. Copy `config-example.yaml` to `config.yaml` and configure
    4. Run `./cloudbridge-client --help` for usage instructions
    
    ## Changelog
  footer: |
    ## Installation Instructions
    
    ### Linux/macOS:
    ```bash
    # Download and extract
    tar -xzf cloudbridge-client_*_linux_amd64.tar.gz
    chmod +x cloudbridge-client
    ./cloudbridge-client --help
    ```
    
    ### Windows:
    ```cmd
    # Download and extract
    # Run cloudbridge-client.exe --help
    ```

# Docker builds disabled - no Dockerfile present
# dockers:
#   - image_templates:
#       - "ghcr.io/2gc-dev/cloudbridge-client:{{ .Version }}"
#       - "ghcr.io/2gc-dev/cloudbridge-client:latest"
#     dockerfile: Dockerfile