# CloudBridge Client Production Configuration

# Relay Configuration
relay:
  host: "b1.2gc.space"  # Новый домен через CDN
  ports:
    http_api: 8080      # HTTP API (Health, Registration)
    p2p_api: 8082      # P2P API (ICE signaling)
    quic: 9091         # QUIC Transport (Main P2P) - обновлен порт
    stun: 19302        # STUN Server (NAT discovery)
    masque: 8443       # HTTPS/MASQUE (Corporate proxy)
    enhanced_quic: 9092 # Enhanced QUIC (Advanced features)
  timeout: "30s"
  tls:
    enabled: true
    min_version: "1.3"
    verify_cert: true
    ca_cert: ""
    client_cert: ""
    client_key: ""
    server_name: "b1.2gc.space"  # Обновляем server_name

# Authentication Configuration
auth:
  type: "jwt"
  secret: "85Sk/NfLq3gqzCXzmBKbJCpL+f5BssXz3G8dVi3sPiE="  # Правильный JWT секрет от DevOps
  fallback_secret: "85Sk/NfLq3gqzCXzmBKbJCpL+f5BssXz3G8dVi3sPiE="  # Fallback секрет
  skip_validation: true               # Отключить валидацию JWT для тестирования
  keycloak:
    enabled: false
    server_url: ""
    realm: ""
    client_id: ""

# Rate Limiting Configuration
rate_limiting:
  enabled: true
  max_retries: 5
  backoff_multiplier: 2.0
  max_backoff: "10s"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Metrics Configuration
metrics:
  enabled: true
  prometheus_port: 9091
  tenant_metrics: true
  buffer_metrics: true
  connection_metrics: true

# Performance Configuration
performance:
  enabled: true
  optimization_mode: "high_throughput"
  gc_percent: 100
  memory_ballast: true

# Tunnel Configuration
tunnel:
  local_port: 3389
  remote_host: "target.2gc.ru"  # Целевой сервер
  remote_port: 3389
  buffer_size: 4096
  max_buffers: 100

# Heartbeat Configuration
heartbeat:
  interval: "10s"
  timeout: "5s"

# ICE Configuration
ice:
  stun_servers:
    - "b1.2gc.space:19302"  # Обновляем STUN сервер
  turn_servers: []
  timeout: "30s"
  max_binding_requests: 7

# QUIC Configuration
quic:
  handshake_timeout: "10s"
  idle_timeout: "30s"
  max_streams: 100
  max_stream_data: 1048576  # 1MB
  keep_alive_period: "15s"
  insecure_skip_verify: false

# P2P Configuration
p2p:
  max_connections: 1000
  session_timeout: "300s"
  peer_discovery_interval: "30s"
  connection_retry_interval: "5s"
  max_retry_attempts: 3

# API Configuration
api:
  base_url: "https://edge.2gc.ru:9444"  # HTTPS production API
  p2p_api_url: "https://edge.2gc.ru:9444"  # HTTPS production API
  insecure_skip_verify: false
  timeout: "30s"
  max_retries: 3
  backoff_multiplier: 2.0
  max_backoff: "60s"