# CloudBridge Relay Client - Example Configuration
# Пример конфигурации для подключения к CloudBridge Relay

# Relay Configuration
relay:
  host: "your-relay-server.com"  # Адрес вашего relay сервера
  port: 8081                     # Порт relay сервера
  base_url: "https://your-relay-server.com:8081"
  timeout: "30s"
  tls:
    enabled: true                # Включить HTTPS
    verify_cert: true
    insecure_skip_verify: false
    server_name: "your-relay-server.com"

# Authentication Configuration
auth:
  type: "jwt"
  token: "YOUR_JWT_TOKEN_HERE"   # Ваш JWT токен от relay сервера
  secret: "YOUR_JWT_SECRET_HERE" # JWT секрет (если используется)
  skip_validation: false
  disable_token_validation: false

# P2P Configuration
p2p:
  server_id: "my-server-001"     # Уникальный ID вашего сервера
  tenant_id: "my-organization"   # ID вашей организации/тенанта
  max_connections: 100
  session_timeout: "300s"
  peer_discovery_interval: "10s"
  connection_retry_interval: "5s"
  max_retry_attempts: 5
  fallback_enabled: true
  derp_fallback: true
  websocket_fallback: true
  auto_relay: true

# ICE Configuration для NAT traversal
ice:
  stun_servers:
    - "your-relay-server.com:19302"  # STUN сервер
    - "stun.l.google.com:19302"      # Backup STUN
  turn_servers:
    - "your-relay-server.com:3478"   # TURN сервер (опционально)
  timeout: "30s"
  max_binding_requests: 7
  connectivity_checks: true
  candidate_gathering: true

# QUIC Configuration
quic:
  handshake_timeout: "10s"
  idle_timeout: "60s"
  max_streams: 100
  max_stream_data: 1048576
  keep_alive_period: "15s"
  insecure_skip_verify: false
  masque_support: true
  http_datagrams: true
  enable_0rtt: true

# WebSocket Configuration (fallback)
websocket:
  enabled: true
  endpoint: "wss://your-relay-server.com:8081/ws/peers"
  timeout: "30s"
  ping_interval: "10s"
  max_reconnect_attempts: 10
  reconnect_delay: "2s"

# Logging Configuration
logging:
  level: "info"                  # debug, info, warn, error
  format: "json"                 # json, text
  output: "stdout"               # stdout, stderr, file

# Metrics Configuration
metrics:
  enabled: true
  prometheus_port: 9091
  tenant_metrics: true
  buffer_metrics: true
  connection_metrics: true
  p2p_metrics: true

# Performance Configuration
performance:
  enabled: true
  optimization_mode: "balanced"  # balanced, high_throughput, low_latency
  gc_percent: 100
  memory_ballast: true
  cpu_profile: false

# Heartbeat Configuration
heartbeat:
  interval: "10s"
  timeout: "5s"
  max_missed: 3

# API Configuration
api:
  base_url: "https://your-relay-server.com:8081"
  p2p_api_url: "https://your-relay-server.com:8081/api/v1/p2p"
  heartbeat_url: "https://your-relay-server.com:8081/api/v1/heartbeat"
  health_url: "https://your-relay-server.com:8081/health"
  metrics_url: "https://your-relay-server.com:8081/metrics"
  timeout: "30s"
  max_retries: 3
  backoff_multiplier: 2.0
  max_backoff: "60s"
