# CloudBridge Client Production Configuration
# Конфигурация для работы с реальными серверами

# Relay Configuration
relay:
  host: "relay.2gc.ru"  # Реальный relay сервер
  port: 9090
  timeout: "30s"
  tls:
    enabled: true
    min_version: "1.3"
    verify_cert: true
    ca_cert: ""
    client_cert: ""
    client_key: ""
    server_name: "relay.2gc.ru"

# Authentication Configuration
auth:
  type: "jwt"
  secret: "${JWT_SECRET}"             # Основной JWT секрет (из переменной окружения)
  fallback_secret: "${FALLBACK_SECRET}"  # Fallback секрет от DevOps (из переменной окружения)
  keycloak:
    enabled: false
    server_url: "https://auth.2gc.ru"
    realm: "cloudbridge"
    client_id: "account"

# Rate Limiting Configuration
rate_limiting:
  enabled: true
  max_retries: 5
  backoff_multiplier: 2.0
  max_backoff: "10s"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Metrics Configuration
metrics:
  enabled: true
  prometheus_port: 9091
  tenant_metrics: true
  buffer_metrics: true
  connection_metrics: true

# Performance Configuration
performance:
  enabled: true
  optimization_mode: "high_throughput"
  gc_percent: 100
  memory_ballast: true

# P2P Mesh Configuration
p2p:
  peer_id: "server-001"
  endpoint: "192.168.1.100:51820"
  public_key: "WG_PUBLIC_KEY"
  private_key: "WG_PRIVATE_KEY"
  mesh_port: 51820

# Tunnel Configuration
tunnel:
  local_port: 3389
  remote_host: "target.2gc.ru"  # Целевой сервер
  remote_port: 3389
  buffer_size: 4096
  max_buffers: 100

# Heartbeat Configuration
heartbeat:
  interval: "10s"
  timeout: "5s"
