# CloudBridge Relay Client - P2P Configuration (Server B)
# P2P конфигурация для сервера B с правильными токенами

# Relay Configuration
relay:
  host: "edge.2gc.ru"
  port: 8081
  base_url: "http://edge.2gc.ru:8081"
  timeout: "30s"
  tls:
    enabled: true
    verify_cert: false
    insecure_skip_verify: true

# Authentication Configuration
auth:
  type: "jwt"
  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIyZ2MucnUiLCJzdWIiOiJzZXJ2ZXItYiIsImF1ZCI6WyJyZWxheS10ZXN0LXRlbmFudCJdLCJleHAiOjE3NjAzMDEwMzAsImlhdCI6MTc1OTA5MTQzMCwicHJvdG9jb2xfdHlwZSI6InAycC1tZXNoIiwidGVuYW50X2lkIjoicmVsYXktdGVzdC10ZW5hbnQiLCJzZXJ2ZXJfaWQiOiJzZXJ2ZXItYiIsImNvbm5lY3Rpb25fdHlwZSI6InF1aWMiLCJwZXJtaXNzaW9ucyI6WyJwMnBfY29ubmVjdCIsInAycF9yZWxheSJdfQ.ZUNG9phxBEKHtviBlxbgp84H4I1YFn24qhUaP6khnto"
  secret: "85Sk/NfLq3gqzCXzmBKbJCpL+f5BssXz3G8dVi3sPiE="
  skip_validation: false

# P2P Configuration
p2p:
  server_id: "server-b"
  tenant_id: "relay-test-tenant"
  max_connections: 100
  session_timeout: "300s"
  peer_discovery_interval: "10s"
  connection_retry_interval: "5s"
  max_retry_attempts: 5
  fallback_enabled: true
  auto_relay: true

# ICE Configuration
ice:
  stun_servers:
    - "edge.2gc.ru:30302"
    - "stun.l.google.com:19302"
  timeout: "30s"
  connectivity_checks: true

# QUIC Configuration
quic:
  handshake_timeout: "10s"
  idle_timeout: "60s"
  keep_alive_period: "15s"
  insecure_skip_verify: true

# API Configuration
api:
  base_url: "http://edge.2gc.ru:8081"
  p2p_api_url: "http://192.168.49.2:32500/api/v1/tenants/relay-test-tenant/peers"
  heartbeat_url: "http://192.168.49.2:32500/api/v1/heartbeat"
  health_url: "http://192.168.49.2:32500/health"
  metrics_url: "http://192.168.49.2:32500/metrics"
  timeout: "30s"
  max_retries: 3
  insecure_skip_verify: true

# WebSocket Configuration
websocket:
  endpoint: "ws://192.168.49.2:32500/ws/peers"
  reconnect_interval: "5s"
  max_reconnect_attempts: 10
  ping_interval: "30s"
  pong_timeout: "10s"

# Logging Configuration
logging:
  level: "debug"
  format: "text"
  output: "stdout"

# Metrics Configuration
metrics:
  enabled: true
  prometheus_port: 9092
