# CloudBridge Client Production Configuration
# Конфигурация для работы с реальными серверами

# Relay Configuration
relay:
  host: "edge.2gc.ru"  # Реальный relay сервер
  ports:
    http_api: 8080      # HTTP API (Health, Registration)
    p2p_api: 8082      # P2P API (ICE signaling)
    quic: 9090         # QUIC Transport (Main P2P)
    stun: 19302        # STUN Server (NAT discovery)
    masque: 8443       # HTTPS/MASQUE (Corporate proxy)
    enhanced_quic: 9092 # Enhanced QUIC (Advanced features)
  timeout: "30s"
  tls:
    enabled: true
    min_version: "1.3"
    verify_cert: true
    ca_cert: ""
    client_cert: ""
    client_key: ""
    server_name: "edge.2gc.ru"

# Authentication Configuration
auth:
  type: "jwt"
  secret: "${JWT_SECRET}"             # Основной JWT секрет (из переменной окружения)
  fallback_secret: "${FALLBACK_SECRET}"  # Fallback секрет от DevOps (из переменной окружения)
  keycloak:
    enabled: false
    server_url: "https://auth.2gc.ru"
    realm: "cloudbridge"
    client_id: "account"

# Rate Limiting Configuration
rate_limiting:
  enabled: true
  max_retries: 5
  backoff_multiplier: 2.0
  max_backoff: "10s"

# Logging Configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Metrics Configuration
metrics:
  enabled: true
  prometheus_port: 9091
  tenant_metrics: true
  buffer_metrics: true
  connection_metrics: true

# Performance Configuration
performance:
  enabled: true
  optimization_mode: "high_throughput"
  gc_percent: 100
  memory_ballast: true

# ICE Configuration
ice:
  stun_servers:
    - "edge.2gc.ru:19302"
  turn_servers: []
  timeout: "30s"
  max_binding_requests: 7

# QUIC Configuration
quic:
  handshake_timeout: "10s"
  idle_timeout: "30s"
  max_streams: 100
  max_stream_data: 1048576  # 1MB
  keep_alive_period: "15s"
  insecure_skip_verify: false

# P2P Configuration
p2p:
  max_connections: 1000
  session_timeout: "300s"
  peer_discovery_interval: "30s"
  connection_retry_interval: "5s"
  max_retry_attempts: 3

# Tunnel Configuration
tunnel:
  local_port: 3389
  remote_host: "target.2gc.ru"  # Целевой сервер
  remote_port: 3389
  buffer_size: 4096
  max_buffers: 100

# Heartbeat Configuration
heartbeat:
  interval: "10s"
  timeout: "5s"

# API Configuration
api:
  base_url: "https://edge.2gc.ru:8080"
  p2p_api_url: "https://edge.2gc.ru:8082"
  insecure_skip_verify: false
  timeout: "30s"
  max_retries: 3
  backoff_multiplier: 2.0
  max_backoff: "60s"
