# CloudBridge Relay Client - Production Configuration
# Production конфигурация для подключения к edge.2gc.ru

# Relay Configuration - Production
relay:
  host: "edge.2gc.ru"         # Production relay сервер
  port: 8081                  # Production порт (настроен в nginx)
  base_url: "http://edge.2gc.ru:8081"
  timeout: "30s"
  tls:
    enabled: false            # HTTP для текущей конфигурации
    verify_cert: false
    insecure_skip_verify: true
    server_name: "edge.2gc.ru"

# Authentication Configuration - Production
auth:
  type: "jwt"
  token: "YOUR_JWT_TOKEN_HERE"  # Замените на ваш JWT токен
  secret: "85Sk/NfLq3gqzCXzmBKbJCpL+f5BssXz3G8dVi3sPiE="
  skip_validation: false
  disable_token_validation: false

# P2P Configuration
p2p:
  server_id: "YOUR_SERVER_ID"   # Замените на ваш server_id
  tenant_id: "YOUR_TENANT_ID"   # Замените на ваш tenant_id
  max_connections: 100
  session_timeout: "300s"
  peer_discovery_interval: "10s"
  connection_retry_interval: "5s"
  max_retry_attempts: 5
  fallback_enabled: true
  derp_fallback: true
  websocket_fallback: true
  auto_relay: true

# ICE Configuration для P2P соединений
ice:
  stun_servers:
    - "edge.2gc.ru:30302"       # Production STUN сервер
    - "stun.l.google.com:19302" # Backup STUN
    - "stun1.l.google.com:19302"
  turn_servers:
    - "edge.2gc.ru:3478"        # TURN сервер (если настроен)
  timeout: "30s"
  max_binding_requests: 7
  connectivity_checks: true
  candidate_gathering: true
  ice_lite: false
  aggressive_nomination: true

# QUIC Configuration
quic:
  handshake_timeout: "10s"
  idle_timeout: "60s"
  max_streams: 100
  max_stream_data: 1048576
  keep_alive_period: "15s"
  insecure_skip_verify: false  # Проверяем сертификаты в production
  masque_support: true
  http_datagrams: true
  enable_0rtt: true

# WebSocket Configuration (fallback)
websocket:
  enabled: true
  endpoint: "ws://edge.2gc.ru:8081/ws/peers"
  timeout: "30s"
  ping_interval: "10s"
  max_reconnect_attempts: 10
  reconnect_delay: "2s"

# Logging Configuration
logging:
  level: "info"               # Production логи
  format: "json"              # JSON для парсинга
  output: "stdout"

# Metrics Configuration
metrics:
  enabled: true
  prometheus_port: 9091
  tenant_metrics: true
  buffer_metrics: true
  connection_metrics: true
  p2p_metrics: true

# Performance Configuration
performance:
  enabled: true
  optimization_mode: "balanced"
  gc_percent: 100
  memory_ballast: true
  cpu_profile: false

# Heartbeat Configuration
heartbeat:
  interval: "10s"
  timeout: "5s"
  max_missed: 3

# API Configuration - Production
api:
  base_url: "http://edge.2gc.ru:8081"
  p2p_api_url: "http://edge.2gc.ru:8081/api/v1/p2p"
  heartbeat_url: "http://edge.2gc.ru:8081/api/v1/heartbeat"
  health_url: "http://edge.2gc.ru:8081/health"
  metrics_url: "http://edge.2gc.ru:8081/metrics"
  timeout: "30s"
  max_retries: 3
  backoff_multiplier: 2.0
  max_backoff: "60s"
  insecure_skip_verify: true

# Security Configuration
security:
  tls_min_version: "1.3"
  cipher_suites: ["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256"]
  verify_peer_certificate: true
  certificate_pinning: false

# Production Environment
production:
  enabled: true
  environment: "production"
  region: "ru-central"
  datacenter: "edge.2gc.ru"