# CloudBridge Client Test Configuration

# Relay Configuration
relay:
  host: "edge.2gc.ru"  # Реальный relay сервер
  port: 9090
  timeout: "30s"
  tls:
    enabled: true
    min_version: "1.3"
    verify_cert: true
    ca_cert: ""
    client_cert: ""
    client_key: ""
    server_name: ""

# Authentication Configuration
auth:
  type: "jwt"
  secret: "${JWT_SECRET}"             # Основной JWT секрет (из переменной окружения)
  fallback_secret: "${FALLBACK_SECRET}"  # Fallback секрет от DevOps (из переменной окружения)
  keycloak:
    enabled: false
    server_url: ""
    realm: ""
    client_id: ""

# Rate Limiting Configuration
rate_limiting:
  enabled: true
  max_retries: 5
  backoff_multiplier: 2.0
  max_backoff: "10s"

# Logging Configuration
logging:
  level: "debug"  # Включаем debug для тестирования
  format: "text"  # Простой формат для тестирования
  output: "stdout"

# Metrics Configuration
metrics:
  enabled: true
  prometheus_port: 9091
  tenant_metrics: true
  buffer_metrics: true
  connection_metrics: true

# Performance Configuration
performance:
  enabled: true
  optimization_mode: "high_throughput"
  gc_percent: 100
  memory_ballast: true

# Tunnel Configuration
tunnel:
  local_port: 3389
  remote_host: "target.2gc.ru"  # Целевой сервер
  remote_port: 3389
  buffer_size: 4096
  max_buffers: 100

# Heartbeat Configuration
heartbeat:
  interval: "10s"
  timeout: "5s"
