name: Pipeline

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g., v1.0.0)'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: '1.25'

jobs:
  # Stage 1: Lint
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Verify go.mod tidy
        run: |
          go mod tidy
          git diff --exit-code -- go.mod go.sum

      - name: Run go vet
        run: go vet ./...

      - name: Install and run golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.64.8
          golangci-lint run --timeout=10m

  # Stage 2: Test
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        run: go test -race -covermode=atomic -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out

  # Stage 3: Security
  security:
    name: Security
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Download dependencies
        run: go mod download

      - name: Run govulncheck
        run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./... || echo "Vulnerabilities found but continuing"

      - name: Run gosec
        uses: securego/gosec@v2.22.0
        continue-on-error: true
        with:
          args: '-fmt sarif -out gosec.sarif -timeout 5m ./...'

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always() && hashFiles('gosec.sarif') != ''
        with:
          sarif_file: gosec.sarif

  # Stage 4: Build Test
  build-test:
    name: Build Test
    runs-on: ubuntu-latest
    needs: security
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test compilation
        run: |
          echo "Testing that code compiles successfully..."
          go build -v ./cmd/cloudbridge-client/
          go build -v ./cmd/quic-tester/
          echo "✅ All binaries compile successfully"

      - name: Clean up test binaries
        run: rm -f cloudbridge-client quic-tester

  # Stage 5: Pre-flight Checks (only for releases)
  pre-flight:
    name: Pre-flight Checks
    runs-on: ubuntu-latest
    needs: build-test
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    outputs:
      version: ${{ steps.version.outputs.version }}
      is_release: ${{ steps.version.outputs.is_release }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Extract version
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            echo "is_release=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.tag }}"
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            VERSION="dev"
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Extracted version: ${VERSION}"

      - name: Verify tag format
        if: steps.version.outputs.is_release == 'true'
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          if [[ ! "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Invalid version format: $VERSION"
            echo "Expected format: v1.2.3"
            exit 1
          fi
          echo "✅ Valid version format: $VERSION"

      - name: Build test with version
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          go mod download
          go build -ldflags="-X main.version=${VERSION}" ./cmd/cloudbridge-client/
          echo "Testing binary with version ${VERSION}:"
          ./cloudbridge-client version | grep "Version:"
          rm cloudbridge-client

  # Stage 6: Release Build & Publish (only for releases)
  release:
    name: Release Build & Publish
    runs-on: ubuntu-latest
    needs: pre-flight
    if: needs.pre-flight.outputs.is_release == 'true'
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.pre-flight.outputs.version }}

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts-${{ needs.pre-flight.outputs.version }}
          path: |
            dist/*.zip
            dist/*.tar.gz
            dist/checksums.txt
          retention-days: 90

  # Summary job
  pipeline-success:
    name: Pipeline Success
    runs-on: ubuntu-latest
    needs: [lint, test, security, build-test, pre-flight, release]
    if: always()
    steps:
      - name: Check pipeline status
        run: |
          echo "=== Pipeline Summary ==="
          echo "Lint: ${{ needs.lint.result }}"
          echo "Test: ${{ needs.test.result }}"  
          echo "Security: ${{ needs.security.result }}"
          echo "Build Test: ${{ needs.build-test.result }}"
          
          if [[ "${{ needs.pre-flight.result }}" != "skipped" ]]; then
            echo "Pre-flight: ${{ needs.pre-flight.result }}"
            echo "Release: ${{ needs.release.result }}"
            echo "🚀 Release pipeline completed!"
          else
            echo "✅ CI pipeline completed!"
          fi
          
          # Check if any required job failed
          if [[ "${{ needs.lint.result }}" != "success" || 
                "${{ needs.test.result }}" != "success" || 
                "${{ needs.security.result }}" != "success" || 
                "${{ needs.build-test.result }}" != "success" ]]; then
            echo "❌ Pipeline failed!"
            exit 1
          fi
          
          # Check release jobs if they ran
          if [[ "${{ needs.pre-flight.result }}" != "skipped" ]]; then
            if [[ "${{ needs.pre-flight.result }}" != "success" || 
                  "${{ needs.release.result }}" != "success" ]]; then
              echo "❌ Release pipeline failed!"
              exit 1
            fi
          fi
          
          echo "✅ Pipeline successful!"
